# Generated by Django 5.0 on 2023-12-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.DateField(verbose_name='Date')),
                ('count', models.CharField(choices=[('People 1', '1'), ('People 2', '2'), ('People 3', '3')], max_length=30, verbose_name='Number of people')),
                ('special', models.TextField(verbose_name='Special Request')),
            ],
        ),
    ]
