# Generated by Django 5.0 on 2023-12-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='count',
            field=models.CharField(choices=[('People 1', 'People 1'), ('People 2', 'People 2'), ('People 3', 'People 3')], max_length=30, verbose_name='Number of people'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=60, verbose_name='Date'),
        ),
    ]
