# Generated by Django 5.0 on 2023-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booking_count_alter_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=50, verbose_name='First line')),
                ('second_line', models.CharField(max_length=50, verbose_name='Second line')),
                ('description', models.TextField(verbose_name='Description')),
                ('button', models.CharField(max_length=50, verbose_name='Button')),
                ('image', models.ImageField(upload_to='index', verbose_name='Image')),
            ],
        ),
    ]
