# Generated by Django 5.0 on 2023-12-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Icon name'),
            preserve_default=False,
        ),
    ]
