# Generated by Django 5.0 on 2023-12-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('profession', models.CharField(max_length=50, verbose_name='Profession')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
