# Generated by Django 5.0 on 2023-12-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(verbose_name='Years Of Experience')),
                ('master_chefs', models.PositiveIntegerField(verbose_name='Popular Master Chefs')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_1', models.ImageField(upload_to='', verbose_name='Image 1')),
                ('image_2', models.ImageField(upload_to='', verbose_name='Image 2')),
                ('image_3', models.ImageField(upload_to='', verbose_name='Image 3')),
                ('image_4', models.ImageField(upload_to='', verbose_name='Image 4')),
            ],
        ),
    ]
